POST https://ma-mairie.herokuapp.com/signup HTTP/1.1
Content-Type: application/json

{
    "pseudo": "Aleks",
    "insee":"51454",
    "password":"oclock123",
    "email":"aleks.oclock@bipbip.fr"
}

###

GET https://ma-mairie.herokuapp.com/ HTTP/1.1

###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "pseudo":"Olive",
    "password":"365",
    "email": "7adad8@bipbip.fr", 
    "insee":"52000"
}