POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "pseudo": "aafa",
    "insee":"51454",
    "password":"fazerf",
    "email":"azef.oclock@bipbip.fr"
}

###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "pseudo":"Micka",
    "password":"oclock123",
    "email": "Micka.oclock@bipbip.fr", 
    "insee":"51454"
}


###
GET http://localhost:3000/admin
Authorization: Bearer
accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJNaWNrYSIsImlhdCI6MTY1MjE4NTI2OH0.qScYE2y6tvkyFaUyXWNP5nz4H33vzeox26Fk3gR8His
