# TEST ENDPOINT SIGNUP
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "pseudo": "adminMairie5",
    "insee":"51454",
    "password":"Mamairie@1",
    "email":"mairie2@gmail.fr"
}


###

# TEST ENDPOINT LOGIN 
POST http://localhost:3003/login HTTP/1.1
Content-Type: application/json

{
    "email": "mairie2@gmail.fr",
    "password":"Mamairie@1"
    
}

# TEST ENDPOINT FOR TOKEN
###
GET http://localhost:3000/admin
Authorization: Bearer
accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJhZG1pbk1haXJpZTIiLCJ0b3duX2hhbGxfaWQiOjEsImlhdCI6MTY1MjI2OTI5MH0.3jwjdh31RvQRYSvBp81TZ8eN1wlgk3zEP-PEJ4v5Kgg
 
