# TEST ENDPOINT SIGNUP
POST http://localhost:3000/signup HTTP/1.1
Content-Type: application/json

{
    "pseudo": "bonbon",
    "insee":"02356",
    "password":"Lololo@1234",
    "email": "lolo@gmail.com"
}

###

# TEST ENDPOINT LOGIN 
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "lolo@gmail.com",
    "password":"Mamairie"
}

